function vtkDataFileVersion34 = import_vtk(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VTKDATAFILEVERSION34 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  VTKDATAFILEVERSION34 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  vtkDataFileVersion34 = importfile("F:\docs\geoentropy\Herten-analog\sim_001.vtk", [11, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Jul-2021 10:05:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [11, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "vtkDataFileVersion34";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
vtkDataFileVersion34 = tbl.vtkDataFileVersion34;
end